### ISSUE TITLE
Discussion: Documentation

### ISSUE THREAD

**Issue by garrytrinder** [GreyHatBeard/m365-etiquette#1]
I propose we use MkDocs and GitHub Pages for this, we already use MkDocs in the Office 365 CLI, is easy to configure, setup and host.

https://www.mkdocs.org/

MkDocs also has a number of themes available, my personal choice would be to use Material design as this is also what PnP uses across all their repos for project documentation.

https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes

**Comment by kevmcdonk** [comment]
I was toying with Alabaster (https://github.com/notpushkin/mkdocs-alabaster) to be slightly less technical as the other PnP ones but could be argued down.

**Comment by kevmcdonk** [comment]
Deploying documentation

**Comment by kevmcdonk** [comment]
Created pages

**Comment by kevmcdonk** [comment]
Created pages

**Comment by kevmcdonk** [comment]
Created pages

**Comment by kevmcdonk** [comment]
Created pages

**Comment by kevmcdonk** [comment]
Created pages

**Comment by kevmcdonk** [comment]
All done and kept Garry happy by sticking with Material!
